## ----------------------------------------
##  Brewfile
## ----------------------------------------
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"

cask_args appdir: "/Applications"

## ========== Base ==========
brew "mas"

## ========== Applications ==========
cask "spectacle"
cask "clipy"
cask "hyperswitch"
cask "google-japanese-ime"

## ========== From App Store ==========
mas "XMind", id: 1327661892
mas "fuwari", id: 1187652334